import { Poller_One } from 'next/font/google';
import './globals.css';

const pollerOne = Poller_One({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pollerOne.className}>{children}</body>
    </html>
  )
}
